name: Testing
on: pull_request

jobs:
  test_hdl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install java
      run: sudo apt-get install default-jdk 
    - name: Run tests
      run: |      
        for file in projects/01/*.tst; do echo "$file"; tools/HardwareSimulator.sh "$file"; done;
        for file in projects/02/*.tst; do echo "$file"; tools/HardwareSimulator.sh "$file"; done;
        for file in projects/03/**/*.tst; do echo "$file"; tools/HardwareSimulator.sh "$file"; done;
        for file in projects/04/**/*.tst; do echo "$file"; tools/CPUEmulator.sh "$file"; done;
        for file in projects/05/*.tst; do echo "$file"; tools/HardwareSimulator.sh "$file"; done;      
    - name: Notify success
      if: success()
      run: echo "Test passed!"
    - name: Notify failure
      if: failure()
      run: echo "Tests failed!"

  test_python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install python3
      run: sudo apt-get install python3.10
    - name: Run tests
      run: |
        for file in projects/06/**/*.asm; do echo "$file"; python3 projects/06/assembler/hack_assembler.py "$file"; done;
        for file in projects/06/**/*-py.hack; do
            echo "Checking $file and ${file/-py.hack/.hack} with PYTHON assembler";
            if cmp -s "$file" "${file/-py.hack/.hack}"; then
                echo "The content of the ${file} and ${file/-py.hack/.hack} are the same"
            else
                echo "The content of the ${file} and ${file/-py.hack/.hack} are different"
            fi
        done;      
    - name: Notify success
      if: success()
      run: echo "Test passed!"
    - name: Notify failure
      if: failure()
      run: echo "Tests failed!"
  
  test_go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install go
      run: sudo apt install golang-go
    - name: Run tests
      run: |
        for file in projects/06/**/*.asm; do echo "$file"; projects/06/go-assembler/main "$file"; done;
        for file in projects/06/**/*-go.hack; do
            echo "Checking $file and ${file/-go.hack/.hack} with GO assembler";
            if cmp -s "$file" "${file/-go.hack/.hack}"; then
                echo "The content of the ${file} and ${file/-go.hack/.hack} are the same"
            else
                echo "The content of the ${file} and ${file/-go.hack/.hack} are different"
            fi
        done;
    - name: Notify success
      if: success()
      run: echo "Test passed!"
    - name: Notify failure
      if: failure()
      run: echo "Tests failed!"
    
