name: Testing
on: [push, pull_request]

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install java
      run: sudo apt-get install default-jdk 
    - name: Make nand2tetris tools executable
      run: find tools/ -type f -iname "*.sh" -exec chmod +x {} +;
    - name: Execute hardware simulator
      run: tools/HardwareSimulator.sh
    - name: Run tests
      run: |      
        for file in projects/01/*.tst; do echo "$file"; tools/HardwareSimulator.sh "$file"; done;
        for file in projects/02/*.tst; do echo "$file"; tools/HardwareSimulator.sh "$file"; done;
        for file in projects/03/**/*.tst; do echo "$file"; tools/HardwareSimulator.sh "$file"; done;
    - name: Notify success
      if: success()
      run: echo "Test passed!"
    - name: Notify failure
      if: failure()
      run: echo "Tests failed!"
  
  # TODO: change how to run tests for next projects
