name: Testing
on: pull_request

jobs:
  test_hdl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run tests
      run: |      
        for file in projects/01/*.tst; do echo "$file"; tools/HardwareSimulator.sh "$file"; done;
        for file in projects/02/*.tst; do echo "$file"; tools/HardwareSimulator.sh "$file"; done;
        for file in projects/03/**/*.tst; do echo "$file"; tools/HardwareSimulator.sh "$file"; done;
        for file in projects/04/**/*.tst; do echo "$file"; tools/CPUEmulator.sh "$file"; done;
        for file in projects/05/*.tst; do echo "$file"; tools/HardwareSimulator.sh "$file"; done;      
    - name: Notify success
      if: success()
      run: echo "Test passed!"
    - name: Notify failure
      if: failure()
      run: echo "Tests failed!"

  test_python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Run tests
      run: |
        for file in projects/06/**/*.asm; do echo "$file"; python3 projects/06/assembler/hack_assembler.py "$file"; done;
        for file in projects/06/**/*-py.hack; do
            echo "Checking $file and ${file/-py.hack/.hack} with PYTHON assembler";
            diff --brief "$file" "${file/-py.hack/.hack}"
        done;      
    - name: Notify success
      if: success()
      run: echo "Test passed!"
    - name: Notify failure
      if: failure()
      run: echo "Tests failed!"
  
  build_go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Build
      run: |
        cd projects/06/go-assembler
        go build -o assembler
        cd
    - name: Upload assembler binary
      uses: actions/upload-artifact@v3
      with:
        name: assembler
        path: projects/06/go-assembler/assembler

  test_go:
    needs: build_go
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download assembler binary from build_go
      uses: actions/download-artifact@v3
      with:
        name: assembler
    - name: Grant executable permission to assembler and move it to projects/06 directory
      run: |
        chmod +x assembler
        mv assembler projects/06/go-assembler
    - name: Run tests
      run: |
        for file in projects/06/**/*.asm; do echo "$file"; projects/06/go-assembler/assembler "$file"; done;
        for file in projects/06/**/*-go.hack; do
            echo "Checking $file and ${file/-go.hack/.hack} with GO assembler";
            diff --brief "$file" "${file/-go.hack/.hack}"
        done;
    - name: Notify success
      if: success()
      run: echo "Test passed!"
    - name: Notify failure
      if: failure()
      run: echo "Tests failed!"
    
